
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: arikan_mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=GuchluBirSifre123!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P GuchluBirSifre123! -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

volumes:
  mssql_data:
